/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                    '#cebdff',
        'on-primary':                 '#35275e',
        'primary-container':          '#4c3e76',
        'on-primary-container':       '#bdaced',
        'primary-fixed':              '#e8ddff',
        'primary-fixed-dim':          '#cebdff',
        'on-primary-fixed':           '#1f1048',
        'on-primary-fixed-variant':   '#4c3e76',
        'inverse-primary':            '#645590',
        'secondary':                  '#bdc7d8',
        'on-secondary':               '#27313e',
        'secondary-container':        '#3d4855',
        'on-secondary-container':     '#acb6c6',
        'secondary-fixed':            '#d9e3f4',
        'secondary-fixed-dim':        '#bdc7d8',
        'on-secondary-fixed':         '#121c28',
        'on-secondary-fixed-variant': '#3d4855',
        'tertiary':                   '#ffb68c',
        'on-tertiary':                '#532200',
        'tertiary-container':         '#763400',
        'on-tertiary-container':      '#fd9f65',
        'tertiary-fixed':             '#ffdbc9',
        'tertiary-fixed-dim':         '#ffb68c',
        'on-tertiary-fixed':          '#321200',
        'on-tertiary-fixed-variant':  '#753400',
        'error':                      '#ffb4ab',
        'on-error':                   '#690005',
        'error-container':            '#93000a',
        'on-error-container':         '#ffdad6',
        'surface-container-lowest':   '#0e0e10',
        'surface-container-low':      '#1b1b1d',
        'surface-container':          '#201f21',
        'surface-container-high':     '#2a2a2c',
        'surface-container-highest':  '#353437',
        'surface':                    '#131315',
        'surface-dim':                '#131315',
        'surface-bright':             '#39393b',
        'surface-variant':            '#353437',
        'on-surface':                 '#e5e1e4',
        'on-surface-variant':         '#cbc3d5',
        'inverse-surface':            '#e5e1e4',
        'inverse-on-surface':         '#313032',
        'surface-tint':               '#cebdff',
        'background':                 '#131315',
        'on-background':              '#e5e1e4',
        'outline':                    '#948e9f',
        'outline-variant':            '#494553',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body:     ['"Inter"',         'sans-serif'],
        label:    ['"Inter"',         'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.25rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
    },
  },
  plugins: [],
};
